### PR TITLE
[CI] Add release pipeline

### PR DESCRIPTION
**Pull request by odesenfans**
Added a release pipeline that builds the package and uploads
it to Pypy.

### CODE REVIEW

**Comment by odesenfans** [comment]
@mhchia for this one I'll need you to create an API token for Pypy and put it in the secrets of the project. Instructions can be found here: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/.

We can try it on the test Pypy first to make sure everything is okay. Could you generate both tokens?

**Comment by mhchia** [comment]
> We can try it on the test Pypy first to make sure everything is okay. Could you generate both tokens?

Both should have been added. :)

**Comment by mhchia** [comment]
What's your username on PyPI? I can add you as a collaborator on PyPI as well, which might be helpful when uploading packages.

**Comment by odesenfans** [comment]
My username is odesenfans on PyPI. As for the CI pipeline, this one won't build automatically on the repository if the pipeline does not exist, so I'll merge this PR first and then adjust to push to PyPI.

**Comment by odesenfans** [comment]
I get the following error when using the test PyPI:

Warning:  It looks like you are trying to use an API token to authenticate in the package index and your token value does not start with "pypi-" as it typically should. This may cause an authentication error. Please verify that you have copied your token properly if such an error occurs.

Could you check out what's going on? Link to the build: https://github.com/mhchia/py-libp2p-daemon-bindings/runs/5083705096?check_suite_focus=true

**Comment by mhchia** [comment]
> My username is odesenfans on PyPI.

Added.

> Could you check out what's going on? Link to the build: https://github.com/mhchia/py-libp2p-daemon-bindings/runs/5083705096?check_suite_focus=true

I generated the API token for test PyPI again twice but CI still failed. Not sure why I will try it again.

**Comment by mhchia** [comment]
I made another PR #54 with your `release.yml` and release CI worked. Not sure if it's an authentication problem on github actions. See https://github.com/mhchia/py-libp2p-daemon-bindings/runs/5104916987?check_suite_focus=true.

Also, I tried to add you as a collaborator on https://test.pypi.org/ but it seems you haven't registered yet.

**Comment by mhchia** [comment]
Sounds good! Added.:)

> I'll use anything in 0.1.x range then and I'll bump the version to 0.2.0 once we're clear.

Sounds good.

**Pull request closed without merging**
