### PR TITLE
Added support for the JavaScript P2P daemon

### PR DESCRIPTION
**Pull request by odesenfans**
Added support for jsp2pd in the tests. The tests now have a
`--daemon` option that can take either "p2pd" for the Go daemon
or "jsp2pd" to use the JavaScript one.

Added two new test markers to skip tests for jsp2pd because
the test:
* uses features that are not implemented in the JS daemon ("go_only")
* fails for an unknown reason that must be investigated
  ("jsp2pd_probable_bug").

### CODE REVIEW

**Comment by odesenfans** [comment]
@mhchia this is the main PR to use either the JS or Go daemons in the tests. In the end I just used features of pytest to skip the tests that fail with the JS daemon, and I kept the system simple for a first PR. I still have to configure the CI, but it seems that the Github API key you used on CircleCI is expired. Could you check it out?

**Comment by mhchia** [comment]
> I still have to configure the CI, but it seems that the Github API key you used on CircleCI is expired. Could you check it out?

Just added a new deploy key, but CI still complains about missing anyio:(

**Review by mhchia — APPROVED** [review]
Awesome work! It's my first time seeing pytest options and it's a pretty neat solution for our case.

**Comment by mhchia** [comment]
Btw. do you have permission to circle CI?

**Comment by odesenfans** [comment]
I just have read-only access. Regarding your issue, I think it's simply because the package is not installed before running tox, something silly like that. Check the order of the commands in the CircleCI file but that seems to be it.

**Comment by odesenfans** [comment]
I'm going to merge this, let's fix the CI issues in another PR later on.

**Comment by mhchia** [comment]
> I'm going to merge this, let's fix the CI issues in another PR later on.

NP. I'm not sure if it works to add you as a collaborator in circle ci, given this [article](https://discuss.circleci.com/t/add-collaborator/3416). If it doesn't work we can switch to github actions which looks more mature now.

**Comment by odesenfans** [comment]
I can set up Github Actions if you wish, I've been playing around with them this week so I should be able to do this quite fast.

**Comment by mhchia** [comment]
> I can set up Github Actions if you wish, I've been playing around with them this week so I should be able to do this quite fast.

That will be great actually!

**Pull request merged**
